
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: check-merge-conflict
  - id: check-ast
  - id: check-json
  - id: check-yaml
  - id: check-docstring-first
  - id: end-of-file-fixer
  - id: requirements-txt-fixer


- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3.9
